<?php

/*
 * @file
 * Drupal Module: raychat
 * Adds the required Javascript for raychat chat to the bottom of all your Drupal pages
 */

/**
 * Implementation of hook_help().
 *
 * @param string $path
 *   router menu path.
 * @param array $arg
 *   array corresponding to return value of arg().
 * @return string
 *   localized string containing help text.
 */
function raychat_help($path, $arg) {
  switch ($path) {
    case 'admin/help#raychat':
      return;
  }
}

/**
 * Implementation of hook_permission().
 *
 * @return array
 *   Array of available permissions
 */
function raychat_permission() {
	return array(
		'administer raychat' => array(
			'title' => t('Administer raychat module'),
			'description' => t('Permission to change raychat settings')
		),
		'use PHP for raychat visibility' => array(
			'title' => t('Use PHP for raychat visibility'),
			'description' => t('Permission to set PHP conditions to customize raychat visibility on various pages')
		)
	);
}

/**
 * Implementation of hook_menu().
 *
 * @return array
 *   structured associative array of menu items.
 */
function raychat_menu() {
  $items['admin/config/system/raychat'] = array(
    'title' => 'raychat',
    'description' => 'Configure the settings used to generate your raychat code.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('raychat_admin_settings_form'),
    'access arguments' => array('administer raychat'),
    'file' => 'raychat.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implementation of hook_page_alter().
 *
 * @global object $user
 *   full user object for current user
 * @param  $page
 *   nested array of renderable elements that make up the page.
 */
function raychat_page_alter(&$page) {
  global $user;
  $id = variable_get('raychat_account', '');
  // 1. Check if the raychat token id has a value.
  // 2. Add JS based on visibility value.
  // 3. Check if we should add the JS for the currently active user's role.
  if (!empty($id) && _raychat_visibility_pages() && _raychat_visibility_user_test($user)) {
    $script = <<<EOS
  document.write(unescape("%3Cscript type='text/javascript'%3E!function () { function t() { var t = document.createElement('script'); t.type = 'text/javascript', t.async = !0, localStorage.getItem('rayToken') ? t.src = 'https://app.raychat.io/scripts/js/' + o + '?rid=' + localStorage.getItem('rayToken') + '&href=' + window.location.href : t.src = 'https://app.raychat.io/scripts/js/' + o; var e = document.getElementsByTagName('script')[0]; e.parentNode.insertBefore(t, e) } var e = document, a = window, o = '{$id}'; 'complete' == e.readyState ? t() : a.attachEvent ? a.attachEvent('onload', t) : a.addEventListener('load', t, !1) }();%3C/script%3E"));
EOS;
    drupal_add_js($script, array('type' => 'inline', 'scope' => 'header'));
  }
}

/**
 * Implementation of hook_requirements().
 *
 * @param string $phase
 *   either 'install' or 'runtime' depending on install or status report page.
 * @return array
 *   associative array of requirements
 */
function raychat_requirements($phase) {
  $requirements = array();
  if ($phase == 'runtime') {
    // Raise warning if raychat user account has not been set yet.
    if (variable_get('raychat_account', false) == false) {
      $requirements['raychat'] = array(
        'title' => t('raychat module'),
        'description' => t('raychat module has not been configured yet. Please configure its settings from the <a href="@url">raychat settings page</a>.', array('@url' => url('admin/settings/raychat'))),
        'severity' => REQUIREMENT_ERROR,
        'value' => t('Not configured'),
      );
    }
  }
  return $requirements;
}

/**
 * Utility function to determing visibility.
 * Based on visibility setting this function returns TRUE if raychat code should
 * be added to the current page and otherwise FALSE.
 *
 * @staticvar boolean $page_match
 *   whether page is visible (true) or not (false).
 * @return boolean
 *   a decision on visibility, true/false
 */
function _raychat_visibility_pages() {
  static $page_match;
  // Cache visibility setting in hook_init for hook_footer.
  if (!isset($page_match)) {
    $visibility = variable_get('raychat_visibility', 0);
    $pages = variable_get('raychat_pages', '');
    // Match path if necessary.
    if (!empty($pages)) {
      if ($visibility < 2) {
        $path = drupal_get_path_alias($_GET['q']);
        // Compare with the internal and path alias (if any).
        $page_match = drupal_match_path($path, $pages);
        if ($path != $_GET['q']) {
          $page_match = $page_match || drupal_match_path($_GET['q'], $pages);
        }
        // When $visibility has a value of 0, the block is displayed on
        // all pages except those listed in $pages. When set to 1, it
        // is displayed only on those pages listed in $pages.
        $page_match = !($visibility xor $page_match);
      }
      elseif (module_exists('php')) {
        $page_match = php_eval($pages);
      }
    }
    else {
      $page_match = TRUE;
    }
  }
  return $page_match;
}

/**
 * Utility function to perform tracking visibility check for an user object.
 *
 * @param object $account
 *   a user object containing an array of roles to check.
 * @return boolean
 *   a decision on if the current user is being tracked by raychat.
 */
function _raychat_visibility_user_test($account) {
  $enabled = FALSE;
  // Is current user a member of a role that should be tracked?
  if (_raychat_visibility_roles($account)) {
    $enabled = TRUE;
  }
  return $enabled;
}

/**
 * Based on visibility setting this function returns TRUE if raychat code should
 * be added for the current role and otherwise FALSE.
 *
 * @param object $account
 *   a full user object.
 * @return boolean
 *   a decision on visibility, true/false
 */
function _raychat_visibility_roles($account) {
  $enabled = TRUE;
  $roles = variable_get('raychat_roles', array());
  if (array_sum($roles) > 0) {
    // One or more roles are selected for tracking.
    foreach (array_keys($account->roles) as $rid) {
      // Is the current user a member of one role selected in admin settings?
      if (isset($roles[$rid]) && $rid == $roles[$rid]) {
        // Current user is a member of a role that is selected in admin settings.
        $enabled = FALSE;
        break;
      }
    }
  }
  return $enabled;
}
